const MONTH_LOOKUP = new Map([
	['00', 'January'],
	['01', 'February'],
	['02', 'March'],
	['03', 'April'],
	['04', 'May'],
	['05', 'June'],
	['06', 'July'],
	['07', 'August'],
	['08', 'September'],
	['09', 'October'],
	['10', 'November'],
	['11', 'December'],
]);
const MONTH_ABBR = new Map([
	['0', 'Jan'],
	['1', 'Feb'],
	['2', 'Mar'],
	['3', 'Apr'],
	['4', 'May'],
	['5', 'Jun'],
	['6', 'Jul'],
	['7', 'Aug'],
	['8', 'Sep'],
	['9', 'Oct'],
	['10', 'Nov'],
	['11', 'Dec'],
]);
const MONTH_ABBR_TO_I = new Map([
	['Jan', '0'],
	['Feb', '1'],
	['Mar', '2'],
	['Apr', '3'],
	['May', '4'],
	['Jun', '5'],
	['Jul', '6'],
	['Aug', '7'],
	['Sep', '8'],
	['Oct', '9'],
	['Nov', '10'],
	['Dec', '11'],
]);
const ALPHA_NUM = new Map([
	['1', 'one'],
	['2', 'two'],
	['3', 'three'],
	['4', 'four'],
	['5', 'five'],
]);
